-- 멤버만들기
CREATE TABLE MEMBER (
    ID INT PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PW VARCHAR2(50) NOT NULL
);


-- 채팅방 만들기
CREATE TABLE CHATTINGROOM (
    CHATTINGROOM_ID INT PRIMARY KEY,
    ROOMNAME VARCHAR(30) NOT NULL,
    UNAME1 INT,
    UNAME2 INT,
    
    
    CONSTRAINT FK_CHATTINGROOM_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGROOM_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID)
);


-- 채팅리스트 만들기
CREATE TABLE CHATTINGLIST (
    CHATTINGLIST_ID INT PRIMARY KEY,
    CHATTINGROOM_ID INT,
    UNAME1 INT,
    UNAME2 INT,
    
    
    CONSTRAINT FK_CHATTINGLIST_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGLIST_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGLIST_ROOM FOREIGN KEY (CHATTINGROOM_ID) REFERENCES CHATTINGROOM(CHATTINGROOM_ID)
    );

-- 채팅메시지 만들기
CREATE TABLE CHATMESSAGE(
    CHATTINGMESSAGE_ID INT PRIMARY KEY,
    UNAME1 INT,
    UNAME2 INT,
    CONTENT VARCHAR(4000),
    REGDATE DATE NOT NULL,
    
    CONSTRAINT FK_CHATMESSAGE_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATMESSAGE_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID)
);



DROP TABLE CHATMESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHATTINGLIST CASCADE CONSTRAINTS;
DROP TABLE CHATTINGROOM CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP SEQUENCE CHATMESSAGE_ID;
DROP SEQUENCE ID;
DROP SEQUENCE CHATTINGROOM_ID;
DROP SEQUENCE CHATTINGLIST_ID;
