CREATE TABLE CHATTINGROOM (
    CHATTINGROOM_ID INT PRIMARY KEY,
    ROOMNAME VARCHAR(30) NOT NULL,
    UNAME1 INT,
    UNAME2 INT,
    
    
    CONSTRAINT FK_CHATTINGROOM_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGROOM_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID)
);

CREATE SEQUENCE CHATTINGROOM_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;





INSERT INTO chattingroom (chattingroom_id , ROOMNAME, UNAME1,UNAME2)
VALUES (CHATTINGROOM_ID.NEXTVAL,'응가방',1,2);

COMMIT;

SELECT * FROM CHATTINGROOM C , MEMBER M WHERE M.ID = C.UNAME1 OR M.ID = C.UNAME2;