CREATE TABLE CHATTINGLIST (
    CHATTINGLIST_ID INT PRIMARY KEY,
    CHATTINGROOM_ID INT,
    UNAME1 INT,
    UNAME2 INT,
    
    
    CONSTRAINT FK_CHATTINGLIST_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGLIST_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATTINGLIST_ROOM FOREIGN KEY (CHATTINGROOM_ID) REFERENCES CHATTINGROOM(CHATTINGROOM_ID)
    );
    
CREATE SEQUENCE CHATTINGLIST_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;