CREATE TABLE CHATMESSAGE(
    CHATTINGMESSAGE_ID INT PRIMARY KEY,
    CHATTINGROOM_ID INT,
    UNAME1 INT,
    CONTENT VARCHAR(4000),
    REGDATE DATE,
    
    CONSTRAINT FK_CHATMESSAGE_ROOMID FOREIGN KEY (CHATTINGROOM_ID) REFERENCES CHATTINGROOM(CHATTINGROOM_ID),
    CONSTRAINT FK_CHATMESSAGE_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID)
);


CREATE SEQUENCE CHATMESSAGE_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;