-- 유저 테이블 생성

CREATE TABLE MEMBER (
    ID INT PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PW VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;


INSERT INTO MEMBER (ID, NAME, NICKNAME, PW)
VALUES (ID.NEXTVAL,'연창현','뿌직','1234');

INSERT INTO MEMBER (ID ,NAME, NICKNAME, PW)
VALUES (ID.NEXTVAL, '김지윤','뿌웅','1234');

INSERT INTO MEMBER (ID ,NAME, NICKNAME, PW)
VALUES (ID.NEXTVAL, '하이','뿌웅','1234');

COMMIT;